### ISSUE TITLE
missing buffer boundary check

### ISSUE THREAD

**Issue by amphineko** [Nat-Lab/eoip#1]
There are some missing checks before performing comparing check between packet headers, the GRE magic and tunnel id.
Bad constructed packet with headers shorter than 8 bytes for EoIP may introduce comparison of memory which are out of current buffered packet and owned by previous packets.

**Comment by amphineko** [comment]
https://github.com/Nat-Lab/eoip/blob/cd13f9900ae8c83210de681dabaa3e9b9a09bf52/eoip.c#L200
```
        if (af == AF_INET) {
          buffer = packet.buffer;
          buffer += packet.ip.ihl * 4;
          len -= packet.ip.ihl * 4;
          if (memcmp(buffer, GRE_MAGIC, 4)) continue;
          ptid = ((uint16_t *) buffer)[3];
          if (ptid != tid) continue;
          buffer += 8;
          len -= 8;
        }
```
This piece of code doesn't check if the buffer has more than 4 bytes while the IPv4 headers are removed.

**Comment by amphineko** [comment]
Ethernet frame length is also not checked against the remaining payload length, and directly passed to the `write` function, which might cause the leak of previous packets.

**Comment by amphineko** [comment]
Feeling lovelorn, poor Naoki. Issue was closed without a reply.

**Comment by magicnat** [comment]
reply & make @amphineko happy.
